#!/bin/bash
flatpak update --noninteractive --assumeyes
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.anydesk.Anydesk
flatpak install flathub org.qbittorrent.qBittorrent
flatpak install flathub net.davidotek.pupgui2
flatpak install flathub com.github.Matoking.protontricks
flatpak install flathub com.heroicgameslauncher.hgl
flatpak install flathub org.wireshark.Wireshark
flatpak install flathub net.lutris.Lutris
flatpak install flathub com.usebottles.bottles
flatpak install flathub org.audacityteam.Audacity
flatpak install flathub org.mozilla.Thunderbird
flatpak install flathub com.ulduzsoft.Birdtray
flatpak install flathub org.onlyoffice.desktopeditors
flatpak install flathub org.libreoffice.LibreOffice
flatpak install flathub org.videolan.VLC
flatpak install flathub org.kde.haruna
flatpak install flathub com.microsoft.Edge
flatpak install flathub com.obsproject.Studio
flatpak install flathub org.gimp.GIMP
flatpak install flathub io.github.hakandundar34coding.system-monitoring-center
flatpak install flathub com.leinardi.gst
flatpak install flathub com.ulduzsoft.Birdtray
flatpak install flathub com.brave.Browser
flatpak install flathub com.steamgriddb.SGDBoop
flatpak install flathub com.visualstudio.code
flatpak install flathub com.bitwarden.desktop
flatpak install flathub org.blender.Blender
flatpak install flathub com.discordapp.Discord
flatpak install flathub org.duckstation.DuckStation
flatpak install flathub net.pcsx2.PCSX2
flatpak install flathub org.mozilla.firefox
flatpak install flathub com.github.tchx84.Flatseal
flatpak install flathub com.google.Chrome
flatpak install flathub org.libretro.RetroArch
flatpak install flathub net.rpcs3.RPCS3
flatpak install flathub com.spotify.Client
flatpak install flathub org.telegram.desktop
flatpak install flathub org.gnome.Weather
echo "Flatpaks installed and updated"